---

- name: Add group karyon
  group: name=karyon gid=1771 state=present
  tags:
    - system
    - karyon-user
    - build

- name: Add  user karyon
  user: name=karyon comment="Karyon Daemon" shell=/bin/bash uid=1771 group=karyon state=present
  tags:
    - system
    - karyon-user
    - build

- name: Create directories
  file: dest=/{{ item }} state=directory mode=0755 owner=karyon group=karyon
  with_items:
    - "{{ karyon_data }}"
    - "{{ karyon_data }}/logs"
  tags:
    - system
    - karyon
    - build

- name: Symlink jetty_logs
  file: src=/{{ karyon_data }}/logs dest=/var/log/karyon owner=karyon group=karyon state=link
  tags:
    - system
    - jetty
    - build

- name: Copy Karyon wrapper
  copy: src=usr/bin/karyon dest=/usr/bin/karyon owner=root group=root mode=0755
  notify:
    - restart karyon
  tags:
    - karyon
    - config
    - build

- name: Create Karyon init.d
  template: src=etc/init.d/karyon dest=/etc/init.d/karyon owner=root group=root mode=0755
  notify:
    - restart karyon
  tags:
    - karyon
    - system
    - build

- name: Create Karyon defaults
  template: src=etc/default/karyon dest=/etc/default/karyon owner=root group=root mode=0644
  notify:
    - restart karyon
  tags:
    - karyon
    - config
    - build

- name: Create logback defaults
  template: src=etc/default/logback.xml dest=/etc/default/logback.xml owner=root group=root mode=0644
  notify:
    - restart karyon
  tags:
    - logback
    - config
    - build

- name: Copy Karyon logrotate.d
  template: src=etc/logrotate.d/karyon dest=/etc/logrotate.d/karyon owner=root group=root mode=0755
  tags:
    - karyon
    - config
    - build

- name: Enable karyon
  service: name=karyon enabled=yes
  tags:
    - build


- name: Configure Security limits soft
  lineinfile: dest=/etc/security/limits.conf line='karyon soft nofile 65535' regexp='^#\ End\ of\ file(.*)' insertafter='^# End of file' state=present
  tags:
    - build

- name: Configure Security limits hard 
  lineinfile: dest=/etc/security/limits.conf line='karyon hard nofile 65535' regexp='^#\ End\ of\ file(.*)' insertafter='^# End of file' state=present
  tags:
    - build