---

- name: restart tomcat7
  service: name=tomcat7 state=restarted
  when: update

- name: reload tomcat7
  service: name=tomcat7 state=reloaded
  when: update

- name: start tomcat7
  service: name=tomcat7 state=started

- name: stop tomcat7
  service: name=tomcat7 state=stopped

- name: enable tomcat7
  service: name=tomcat7 enabled=yes
  when: deploy is defined