---

# Jetty Version
jetty_version: 8.1.17.v20150415
jetty_url: http://eclipse.org/downloads/download.php?file=/jetty/stable-8/dist/jetty-distribution-{{ jetty_version }}.tar.gz&r=1

# FS vars
jetty_home: "{{ kenzanmedia_apps }}/jetty8"
jetty_data: "{{ kenzanmedia_data }}/jetty8"
jetty_logs: "{{ jetty_data }}/logs"
jetty_webapps: "{{ kenzanmedia_apps }}/webapps"

# Jetty files to remove
jetty_remove:
  - /contexts/test.xml
  - /contexts/javadoc.xml
  - /contexts/test.d

## Resources
# Heap
# Percent of total memory to use for heap size
xmx_percent: .8
# Percent of total memory to use for start heap
xms_percent: .2
