---
- name: Download terraform
  get_url: url={{ terraform_url }} dest=/tmp/terraform{{ terraform_version }}.zip owner=root group=root mode=0644
  tags:
    - system
    - build
    - terraform

- name: Extract terraform
  command: unzip /tmp/terraform{{ terraform_version }}.zip -d /usr/bin chdir=/tmp
  tags:
    - system
    - build
    - terraform
